version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: "5432:5432"
      DB_USER: admin
      DB_PASSWORD: 12345
      DB_NAME: shopper
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    volumes:
      - ./src:/usr/src/app/src
    command: npm run dev
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - db

  db:
    image: postgres:14
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: shopper
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork: